package com.Cars.Model;

import java.io.Serializable;

/**
 * YuDing モデルクラス.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class YuDing implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** UserID. */
	private Integer userid;

	/** Name. */
	private String name;

	/** Sex. */
	private String sex;

	/** CarID. */
	private Integer carid;

	/** DianHua. */
	private Integer dianhua;

	/** qq. */
	private Integer qq;

	/** weixin. */
	private Integer weixin;

	/** DiZhi. */
	private String dizhi;

	/**
	 * コンストラクタ.
	 */
	public YuDing() {
	}

	/**
	 * UserID を設定します.
	 * 
	 * @param userid
	 *            UserID
	 */
	public void setUserid(Integer userid) {
		this.userid = userid;
	}

	/**
	 * UserID を取得します.
	 * 
	 * @return UserID
	 */
	public Integer getUserid() {
		return this.userid;
	}

	/**
	 * Name を設定します.
	 * 
	 * @param name
	 *            Name
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * Name を取得します.
	 * 
	 * @return Name
	 */
	public String getName() {
		return this.name;
	}

	/**
	 * Sex を設定します.
	 * 
	 * @param sex
	 *            Sex
	 */
	public void setSex(String sex) {
		this.sex = sex;
	}

	/**
	 * Sex を取得します.
	 * 
	 * @return Sex
	 */
	public String getSex() {
		return this.sex;
	}

	/**
	 * CarID を設定します.
	 * 
	 * @param carid
	 *            CarID
	 */
	public void setCarid(Integer carid) {
		this.carid = carid;
	}

	/**
	 * CarID を取得します.
	 * 
	 * @return CarID
	 */
	public Integer getCarid() {
		return this.carid;
	}

	/**
	 * DianHua を設定します.
	 * 
	 * @param dianhua
	 *            DianHua
	 */
	public void setDianhua(Integer dianhua) {
		this.dianhua = dianhua;
	}

	/**
	 * DianHua を取得します.
	 * 
	 * @return DianHua
	 */
	public Integer getDianhua() {
		return this.dianhua;
	}

	/**
	 * qq を設定します.
	 * 
	 * @param qq
	 *            qq
	 */
	public void setQq(Integer qq) {
		this.qq = qq;
	}

	/**
	 * qq を取得します.
	 * 
	 * @return qq
	 */
	public Integer getQq() {
		return this.qq;
	}

	/**
	 * weixin を設定します.
	 * 
	 * @param weixin
	 *            weixin
	 */
	public void setWeixin(Integer weixin) {
		this.weixin = weixin;
	}

	/**
	 * weixin を取得します.
	 * 
	 * @return weixin
	 */
	public Integer getWeixin() {
		return this.weixin;
	}

	/**
	 * DiZhi を設定します.
	 * 
	 * @param dizhi
	 *            DiZhi
	 */
	public void setDizhi(String dizhi) {
		this.dizhi = dizhi;
	}

	/**
	 * DiZhi を取得します.
	 * 
	 * @return DiZhi
	 */
	public String getDizhi() {
		return this.dizhi;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((userid == null) ? 0 : userid.hashCode());

		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		YuDing other = (YuDing) obj;
		if (userid == null) {
			if (other.userid != null) {
				return false;
			}
		} else if (!userid.equals(other.userid)) {
			return false;
		}

		return true;
	}

}
